### ISSUE TITLE
Small documentation about how to use the resume playback features

### ISSUE THREAD

**Issue by quimodotcom** [sonallux/spotify-web-api-java#69]

**Comment by sonallux** [comment]
As this library is entirely generated from Spotify's Web API reference documentation, adding more documentation about endpoints is out of scope for this library.

Resuming playback is possible via this method on the `PlayerApi`: https://github.com/sonallux/spotify-web-api-java/blob/232eb55a14309a0c111dbd187a76ccc0ac445d7b/spotify-web-api-java/src/main/generated/de/sonallux/spotify/api/apis/PlayerApi.java#L118-L125

If you need more info about this endpoint please consult the [reference documentation](https://developer.spotify.com/documentation/web-api/reference/#endpoint-start-a-users-playback) or post a question in the [Spotify for Developer forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
